using System.Linq;
using UnityEngine;

public static class Colors
{
    public static Color32 FromHex(string hex, byte alpha = 255)
    {
        if (hex[0] == '#')
            hex = hex[1..];

        if (hex.Length == 3)
            hex = string.Concat(hex.Select(c => $"{c}{c}"));

        var r = byte.Parse(hex[0..2], System.Globalization.NumberStyles.HexNumber);
        var g = byte.Parse(hex[2..4], System.Globalization.NumberStyles.HexNumber);
        var b = byte.Parse(hex[4..6], System.Globalization.NumberStyles.HexNumber);

        return new(r, g, b, alpha);
    }

    public static Color32 FromHex(string hex, float alpha) =>
        FromHex(hex, (byte)(alpha * 255));

    public static string ToHex(Color32 color) => $"{color.r:X2}{color.g:X2}{color.b:X2}";

    public static Color aliceblue = FromHex("#f0f8ff");
    public static Color antiquewhite = FromHex("#faebd7");
    public static Color aqua = FromHex("#00ffff");
    public static Color aquamarine = FromHex("#7fffd4");
    public static Color azure = FromHex("#f0ffff");
    public static Color beige = FromHex("#f5f5dc");
    public static Color bisque = FromHex("#ffe4c4");
    public static Color black = FromHex("#000000");
    public static Color blanchedalmond = FromHex("#ffebcd");
    public static Color blue = FromHex("#0000ff");
    public static Color blueviolet = FromHex("#8a2be2");
    public static Color brown = FromHex("#a52a2a");
    public static Color burlywood = FromHex("#deb887");
    public static Color cadetblue = FromHex("#5f9ea0");
    public static Color chartreuse = FromHex("#7fff00");
    public static Color chocolate = FromHex("#d2691e");
    public static Color coral = FromHex("#ff7f50");
    public static Color cornflowerblue = FromHex("#6495ed");
    public static Color cornsilk = FromHex("#fff8dc");
    public static Color crimson = FromHex("#dc143c");
    public static Color cyan = FromHex("#00ffff");
    public static Color darkblue = FromHex("#00008b");
    public static Color darkcyan = FromHex("#008b8b");
    public static Color darkgoldenrod = FromHex("#b8860b");
    public static Color darkgray = FromHex("#a9a9a9");
    public static Color darkgreen = FromHex("#006400");
    public static Color darkgrey = FromHex("#a9a9a9");
    public static Color darkkhaki = FromHex("#bdb76b");
    public static Color darkmagenta = FromHex("#8b008b");
    public static Color darkolivegreen = FromHex("#556b2f");
    public static Color darkorange = FromHex("#ff8c00");
    public static Color darkorchid = FromHex("#9932cc");
    public static Color darkred = FromHex("#8b0000");
    public static Color darksalmon = FromHex("#e9967a");
    public static Color darkseagreen = FromHex("#8fbc8f");
    public static Color darkslateblue = FromHex("#483d8b");
    public static Color darkslategray = FromHex("#2f4f4f");
    public static Color darkslategrey = FromHex("#2f4f4f");
    public static Color darkturquoise = FromHex("#00ced1");
    public static Color darkviolet = FromHex("#9400d3");
    public static Color deeppink = FromHex("#ff1493");
    public static Color deepskyblue = FromHex("#00bfff");
    public static Color dimgray = FromHex("#696969");
    public static Color dimgrey = FromHex("#696969");
    public static Color dodgerblue = FromHex("#1e90ff");
    public static Color firebrick = FromHex("#b22222");
    public static Color floralwhite = FromHex("#fffaf0");
    public static Color forestgreen = FromHex("#228b22");
    public static Color fuchsia = FromHex("#ff00ff");
    public static Color gainsboro = FromHex("#dcdcdc");
    public static Color ghostwhite = FromHex("#f8f8ff");
    public static Color goldenrod = FromHex("#daa520");
    public static Color gold = FromHex("#ffd700");
    public static Color gray = FromHex("#808080");
    public static Color green = FromHex("#008000");
    public static Color greenyellow = FromHex("#adff2f");
    public static Color grey = FromHex("#808080");
    public static Color honeydew = FromHex("#f0fff0");
    public static Color hotpink = FromHex("#ff69b4");
    public static Color indianred = FromHex("#cd5c5c");
    public static Color indigo = FromHex("#4b0082");
    public static Color ivory = FromHex("#fffff0");
    public static Color khaki = FromHex("#f0e68c");
    public static Color lavenderblush = FromHex("#fff0f5");
    public static Color lavender = FromHex("#e6e6fa");
    public static Color lawngreen = FromHex("#7cfc00");
    public static Color lemonchiffon = FromHex("#fffacd");
    public static Color lightblue = FromHex("#add8e6");
    public static Color lightcoral = FromHex("#f08080");
    public static Color lightcyan = FromHex("#e0ffff");
    public static Color lightgoldenrodyellow = FromHex("#fafad2");
    public static Color lightgray = FromHex("#d3d3d3");
    public static Color lightgreen = FromHex("#90ee90");
    public static Color lightgrey = FromHex("#d3d3d3");
    public static Color lightpink = FromHex("#ffb6c1");
    public static Color lightsalmon = FromHex("#ffa07a");
    public static Color lightseagreen = FromHex("#20b2aa");
    public static Color lightskyblue = FromHex("#87cefa");
    public static Color lightslategray = FromHex("#778899");
    public static Color lightslategrey = FromHex("#778899");
    public static Color lightsteelblue = FromHex("#b0c4de");
    public static Color lightyellow = FromHex("#ffffe0");
    public static Color lime = FromHex("#00ff00");
    public static Color limegreen = FromHex("#32cd32");
    public static Color linen = FromHex("#faf0e6");
    public static Color magenta = FromHex("#ff00ff");
    public static Color maroon = FromHex("#800000");
    public static Color mediumaquamarine = FromHex("#66cdaa");
    public static Color mediumblue = FromHex("#0000cd");
    public static Color mediumorchid = FromHex("#ba55d3");
    public static Color mediumpurple = FromHex("#9370db");
    public static Color mediumseagreen = FromHex("#3cb371");
    public static Color mediumslateblue = FromHex("#7b68ee");
    public static Color mediumspringgreen = FromHex("#00fa9a");
    public static Color mediumturquoise = FromHex("#48d1cc");
    public static Color mediumvioletred = FromHex("#c71585");
    public static Color midnightblue = FromHex("#191970");
    public static Color mintcream = FromHex("#f5fffa");
    public static Color mistyrose = FromHex("#ffe4e1");
    public static Color moccasin = FromHex("#ffe4b5");
    public static Color navajowhite = FromHex("#ffdead");
    public static Color navy = FromHex("#000080");
    public static Color oldlace = FromHex("#fdf5e6");
    public static Color olive = FromHex("#808000");
    public static Color olivedrab = FromHex("#6b8e23");
    public static Color orange = FromHex("#ffa500");
    public static Color orangered = FromHex("#ff4500");
    public static Color orchid = FromHex("#da70d6");
    public static Color palegoldenrod = FromHex("#eee8aa");
    public static Color palegreen = FromHex("#98fb98");
    public static Color paleturquoise = FromHex("#afeeee");
    public static Color palevioletred = FromHex("#db7093");
    public static Color papayawhip = FromHex("#ffefd5");
    public static Color peachpuff = FromHex("#ffdab9");
    public static Color peru = FromHex("#cd853f");
    public static Color pink = FromHex("#ffc0cb");
    public static Color plum = FromHex("#dda0dd");
    public static Color powderblue = FromHex("#b0e0e6");
    public static Color purple = FromHex("#800080");
    public static Color rebeccapurple = FromHex("#663399");
    public static Color red = FromHex("#ff0000");
    public static Color rosybrown = FromHex("#bc8f8f");
    public static Color royalblue = FromHex("#4169e1");
    public static Color saddlebrown = FromHex("#8b4513");
    public static Color salmon = FromHex("#fa8072");
    public static Color sandybrown = FromHex("#f4a460");
    public static Color seagreen = FromHex("#2e8b57");
    public static Color seashell = FromHex("#fff5ee");
    public static Color sienna = FromHex("#a0522d");
    public static Color silver = FromHex("#c0c0c0");
    public static Color skyblue = FromHex("#87ceeb");
    public static Color slateblue = FromHex("#6a5acd");
    public static Color slategray = FromHex("#708090");
    public static Color slategrey = FromHex("#708090");
    public static Color snow = FromHex("#fffafa");
    public static Color springgreen = FromHex("#00ff7f");
    public static Color steelblue = FromHex("#4682b4");
    public static Color tan = FromHex("#d2b48c");
    public static Color teal = FromHex("#008080");
    public static Color thistle = FromHex("#d8bfd8");
    public static Color tomato = FromHex("#ff6347");
    public static Color turquoise = FromHex("#40e0d0");
    public static Color violet = FromHex("#ee82ee");
    public static Color wheat = FromHex("#f5deb3");
    public static Color white = FromHex("#ffffff");
    public static Color whitesmoke = FromHex("#f5f5f5");
    public static Color yellow = FromHex("#ffff00");
    public static Color yellowgreen = FromHex("#9acd32");
}